src/DigitalBiobank/urls.py
from django.conf.urls import url ,include
from django.urls import path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    path('', include('MainApp.urls',namespace='MainApp')),
    url(r'^ManageUsers/', include('ManageUsers.urls', namespace='ManageUsers')),
    url(r'^Report/', include('Report.urls',namespace='Report')),    
    # url(r'^Project/', include('Project.urls',namespace='Project')),
    url(r'^upload/', include('Upload.urls',namespace='upload')),    
    # url(r'^runpipeline/', include('RunPipeline.urls',namespace='runpipeline')),        
    # url(r'^socket/', include('ChatRoom.urls',namespace='socket')),        
    # url(r'^auth/', include('social_django.urls', namespace='social')),
]

src/MainApp/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.views.static import serve
from django.conf import settings
from MainApp.helper import decode_url
from django.shortcuts import redirect

app_name = 'MainApp'

# @login_required
# def protected_serve(request, path, document_root=None, show_indexes=False):
#     if 'storage' in path:
#         pathh = path.split('/')
#         user_id = str(request.user.id)
#         check_uid = decode_url(pathh[2]).split('.')
#         if check_uid[0] != user_id:
#             return redirect('/ManageUsers/logout/')
#     return serve(request, path, document_root, show_indexes)

# set url with function in view Metagenomic

urlpatterns = [
    url(r'^$', views.index),
    url(r'^home', views.index, name='home'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^about', views.about, name='about'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^help', views.help, name='help'),
    # url(r'^run_celery_email_ncbi', views.run_celery_email_ncbi),
    path('check_celery/<str:celery_id>/', views.check_celery_id),



    # url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], protected_serve, {'document_root': settings.MEDIA_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

src/ManageUsers/urls.py
from django.conf.urls import include, url
from . import views , views_admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
app_name = 'ManageUsers'

#set name url with function in views  manage user

urlpatterns = [
    url(r'^UserSignup/$', views.UserSignup, name='UserSignup'),
    # url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^status_message', views.status_message, name='status_message'),
    url(r'^user/validate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate_account, name='activate_account'),
    url(r'^user/reset/password/request/$', views.password_reset_request,
        name='password_reset_request'),
    url(r'^user/reset/password/validate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/(?P<date>[0-9A-Za-z_\-]+)/(?P<time>[0-9A-Za-z_\-]+)/$',
        views.activate_password_reset, name='activate_password_reset'),
    url(r'^user/reset/password/change/$', views.reset_change_password_request,
        name='reset_change_password'),
    url(r'^user/change_password/$', views.change_password,
        name='change_password'),
    url(r'^ProfileSetting/$', views.user_profile, name='ProfileSetting'),
    url(r'^AdminApproved/$', views_admin.admin_approved_user, name='AdminApproved'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

src/Report/urls.py
from django.conf.urls import url
from . import views
from Report.views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path

app_name = 'Report'
# set name url with views report application
urlpatterns = [
    path('pdf/', PDF.as_view(),name='pdf'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

src/ManageUsers/models.py
from django.db import models
from django.contrib.auth.models import User , Group
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now

class user_profile(models.Model):
    user = models.OneToOneField(User ,on_delete=models.PROTECT)
    nationd_id = models.CharField(max_length=255, blank=True, null=True)
    mobile_tel = models.CharField(max_length=255, blank=True, null=True)
    organization = models.CharField(max_length=255, blank=True, null=True)
    sub_organization = models.CharField(max_length=255, blank=True, null=True)
    department = models.CharField(max_length=255, blank=True, null=True)
    approved_admin_id = models.IntegerField(default='0')
    user_agree = models.CharField(max_length=5, blank=True, null=True)
    img_profile = models.ImageField(upload_to = 'img_profile/', default = 'img_profile/blank_profile.png')

class user_task(models.Model):
    id = models.AutoField(primary_key=True)
    task_id = models.CharField(max_length=255, blank=True, null=True)
    datetime_create = models.DateTimeField(default=now, editable=False, blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

src/ManageUsers/views.py
from django.contrib.auth import login as dj_login, logout as dj_logout
from django.shortcuts import render, redirect ,HttpResponse
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from .tokens import account_activation_token
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.conf import settings
from django.core.mail import EmailMessage
import os.path
from .forms import AdminFormSignup, LoginForm , UserFormSignup , ResetChangePasswordForm, ChangePasswordForm ,PasswordResetRequestForm

from datetime import datetime
from django.utils.translation import ugettext_lazy as _

from django.db import connection
from .models import user_profile as db_profile


# home page for user
homePath = '/home/'
dashboardPath = '/dashboard/'
# other page
projectPath = '/ManageUsers'
loginPath = '/home/'
adminPage = '/ManageUsers/AdminApproved/'



# Signup function
def UserSignup(request):
    args = {}

    if request.method == 'POST':
        form = UserFormSignup(request.POST)

        # Check register button
        if 'registerbtn' in request.POST:
            if form.is_valid():
                user = form.save()
                user = User.objects.filter(username=form.cleaned_data.get('username')).first()

                # email confirmation
                current_site = get_current_site(request)
                subject = _('Confirm registration from Metagenomic')
                message = render_to_string('acc_active_email.html', {
                    'user': user,
                    'domain': current_site,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                    'detail': 'คลิกเพื่อทำการอนุมัติ'
                })
                user.email_user(subject, message)
                message_header =_('Register successfully.')
                message_detail =_('Please confirm your email.')
                message_header_json = str(message_header)
                message_detail_json = str(message_detail)
                request.session['sm_value'] = {'message_header': message_header_json,
                                               'message_detail': message_detail_json,
                                               'type': 'success',
                                               'displaytime': '10'}
                request.session['goto'] = homePath

                return redirect(projectPath+'/status_message/')

            else:
                print(form.errors.as_data())

    else:
        # if not post show form signup
        form = UserFormSignup()

    args['form'] = form
    return render(request, 'user_signup.html', args)


# Signup function
def AdminSignup(request):
    args = {}

    if request.method == 'POST':
        form = AdminFormSignup(request.POST)

        # Check register button
        if 'registerbtn' in request.POST:
            if form.is_valid():
                user = form.save()
                user = User.objects.filter(username=form.cleaned_data.get('username')).first()

                # email confirmation
                current_site = get_current_site(request)
                subject = _('Confirm registration from Metagenomic')
                message = render_to_string('acc_active_email.html', {
                    'user': user,
                    'domain': current_site,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode,
                    'token': account_activation_token.make_token(user),
                })
                user.email_user(subject, message)
                message_header =_('Register successfully.')
                message_detail =_('Please confirm your email.')
                message_header_json = str(message_header)
                message_detail_json = str(message_detail)
                request.session['sm_value'] = {'message_header': message_header_json,
                                               'message_detail': message_detail_json,
                                               'type': 'success',
                                               'displaytime': '10'}
                request.session['goto'] = homePath

                return redirect(projectPath+'/status_message/')

            else:
                print(form.errors.as_data())

    else:
        # if not post show form signup
        form = AdminFormSignup()

    args['form'] = form
    return render(request, 'admin_signup.html', args)


#json in array for row
def dictfetchall(cursor): 
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

# Login function
def login(request):     
    args = {}
    form = LoginForm(request.POST or None)

    # check if post button login check user pass
    if request.method == 'POST':
        if 'loginBtn' in request.POST and form.is_valid():

            user = form.login(request)
            request.user.id = user.id
            user_id = request.user.id
            # check new user create storage folder
            check_create_storage(request)

            cursor = connection.cursor()
            cursor.execute("SELECT auth_group.name as group_name \
                            FROM auth_group , auth_user_groups \
                            WHERE auth_group.id = auth_user_groups.group_id \
                            AND auth_user_groups.user_id = \'"+ str(user_id) +"\'")
            row = dictfetchall(cursor)
            for i in row:
                group_name = str(i["group_name"])
            
            if user is not None:
                if group_name == 'admin':
                    dj_login(request, user)
                    if 'next' in request.POST:
                        return redirect(adminPage)
                    return redirect(adminPage)
                elif group_name == 'user':
                    dj_login(request, user)
                    if 'next' in request.POST:
                        next_to = request.GET.get('next')
                        return redirect(next_to)
                    return redirect(dashboardPath)

                
                return redirect('/ManageUser/logout')

        elif 'test' in request.POST:
            message_header =_('Register successfully.')
            message_detail =_('Please confirm your email.')
            message_header_json = str(message_header)
            message_detail_json = str(message_detail)
            request.session['sm_value'] = {'message_header': message_header_json,
                                           'message_detail': message_detail_json,
                                           'type': 'success',
                                           'displaytime': '10'}
            request.session['goto'] = homePath


            return redirect(projectPath + '/status_message/')

    args['form'] = form

    if request.user.is_authenticated:
        user_id = request.user.id
        cursor = connection.cursor()
        cursor.execute("SELECT auth_group.name as group_name \
                        FROM auth_group , auth_user_groups \
                        WHERE auth_group.id = auth_user_groups.group_id \
                        AND auth_user_groups.user_id = \'"+ str(user_id) +"\'")
        row = dictfetchall(cursor)
        for i in row:
            group_name = str(i["group_name"])

        if group_name == 'user':
            return redirect(homePath)
            # return HttpResponse('user_page')
        elif group_name == 'admin':
            return redirect(adminPage)
            # return HttpResponse('user_page')
        else:
            return redirect('/ManageUsers/logout')

    return render(request, 'login.html', args)


def activate_account(request, uidb64, token):

    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        #dj_login(request, user)
        message_header =_('Confirm email successfully.')
        message_detail =_('Enjoy using our system.')
        message_header_json = str(message_header)
        message_detail_json = str(message_detail)
        request.session['sm_value'] = {'message_header': message_header_json,
                                       'message_detail': message_detail_json,
                                       'type': 'success',
                                       'displaytime': '5'}
        request.session['goto'] = loginPath

        return redirect(projectPath+'/status_message/')
    else:
        message_header =_('Confirm email failed.')
        message_detail =_('Please contact officer.')
        message_header_json = str(message_header)
        message_detail_json = str(message_detail)
        request.session['sm_value'] = {'message_header': message_header_json,
                                       'message_detail': message_detail_json,
                                       'type': 'text-center',
                                       'displaytime': '5'}

        request.session['goto'] = homePath


        return redirect(projectPath+'/status_message/')


# Check and Create folder
def check_create_storage(request):

    try:
        user_id = request.session.get('user_id')
        path = str(user_id)
        default_path = os.path.abspath(settings.MEDIA_ROOT+"/storage/"+path)
        if not os.path.exists(settings.MEDIA_ROOT+"/storage/"+path):
            os.makedirs(default_path)
    except OSError as e:
        if e.errno == 17:
            return False

src/ManageUsers/templates/404_page.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<style>
        body {
            background: #dedede;
        }
        .page-wrap {
            min-height: 100vh;
        }
</style>
<meta http-equiv="refresh" content="1;url=/home/">
<div class="page-wrap d-flex flex-row align-items-center">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12 text-center">
                    <span class="display-1 d-block">404</span>
                    <div class="mb-4 lead">The page you are looking for was not found.</div>
                    <a href="/ManageUsers/login" class="btn btn-link">Back to Home</a>
                </div>
            </div>
        </div>
    </div>
    

src/ManageUsers/templates/acc_active_email.html
{% autoescape off %}
{% load i18n %}
{% trans "Hello" %} {{ user.get_full_name }},
{% trans "Click link to comfirm" %} ,
http://{{ domain }}{% url 'ManageUsers:activate_account' uidb64=uid token=token %}

{% endautoescape %}

src/ManageUsers/templates/acc_reset_password_email.html
{% load i18n %}
{% autoescape off %}
    {% trans "Hello" %} {{ user.get_full_name }},
    {% trans "Click link to confirm a password" %},
    http://{{ domain }}{% url 'ManageUsers:activate_password_reset' uidb64=uid token=token date=date time=time %}


    {% trans "Note: The 30 minute expired then make a new request." %} 
{% endautoescape %}

src/ManageUsers/templates/login.html
{% extends "base_not_nav.html" %}
{% load staticfiles %}
{% load i18n %}
{% block document_container %}



    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center p-5">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body">
                        <!-- Nested Row within Card Body -->
                        <div class="row">

                            <div class="col-lg-12">
                                <div class="p-3">
                                    <div class="text-center">
                                        <h1 class="h5 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>

                                    <form class="user" method="POST">
                                        {% csrf_token %}

                                        <div class="form-group form-primary">
                                            {% if request.GET.next %}
                                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                                            {% endif %}
                                            {{form.username }}
                                            <span class="form-bar"></span>
                                            {% comment %} <label class="float-label">Email</label> {% endcomment %}
                                        </div>
                                        <div class="form-group form-primary">
                                            {{form.password }}
                                            <span class="form-bar"></span>
                                            {% comment %} <label class="float-label">Password</label> {% endcomment %}
                                        </div>
                                        {% if form.non_field_errors %} {% for error in form.non_field_errors %}
                                        <div class="alert alert-warning" role="alert">{{ error }}</div>
                                        {% endfor %} {% endif %}
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember
                                                    Me</label>
                                            </div>
                                        </div>
                                        <div class="row text-left">
                                            <div class="col-12">

                                                <div class="forgot-phone text-right float-right">
                                                    <a href="{% url 'ManageUsers:password_reset_request' %}"
                                                        class="text-right f-w-600"> Forgot
                                                        Password?</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row mt-2">
                                            <div class="col-md-12">
                                                <button class="btn btn-primary btn-user btn-block" name="loginBtn"
                                                    type="submit">Sign in</button>
                                            </div>
                                        </div>
                                        <p class="text-inverse text-left mt-3">Don't have an account?
                                            <a href="/ManageUsers/UserSignup/">
                                                <b>
                                                    <u>
                                                        Register here
                                                    </u>
                                                </b>
                                            </a>
                                        </p>
                                    </form>
                                    <hr>


                                    <a href="{% url 'social:begin' 'google-oauth2' %}">
                                        <img src="{% static 'img/main-img/google-img/btn_google_dark_normal_ios.svg' %}"
                                            class="img-fluid" alt="Responsive image">
                                    </a>


                                    <a id="if_fb" href="{% url 'social:begin' 'facebook' %}">
                                        <img src="{% static 'img/main-img/facebook-img/f_logo_RGB-Blue_58.png' %}"
                                            class="img-fluid" alt="Responsive image" width="5%">
                                    </a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock document_container %}

src/ManageUsers/templates/user_acc_active_email.html
{% autoescape off %}
{% load i18n %}
{% trans "Hello" %} {{ user.get_full_name }}, {% trans "from" %} {{domain}}


{{ detail }}

{% endautoescape %}

src/ManageUsers/templates/user_signup.html
{% extends "base_not_nav.html" %}
{% load staticfiles %}
{% load i18n %}
{% block document_container %}


    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center p-5">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body">
                        <form class="p-4" method="POST" autocomplete="off">
                            {% csrf_token %}
                            <div class="row m-b-20">
                                <div class="col-md-12">
                                    <h3 class="text-center txt-primary">Sign Up</h3>
                                </div>
                            </div>
                            <p class="text-muted text-center ">Sign up with your regular account</p>

                            <div class="row pb-2">
                                <div class="col-sm-12">
                                 <label>{{form.username.label}}:</label>
                                   {{form.username}}
                                   {{form.errors.username}}
                                </div>
                            </div>
                            
                            <div class="pt-0 pb-2">
                                <label>{{form.email.label}}:</label>
                                {{form.email}}
                                {{form.errors.email}}
                                <span class="form-bar"></span>
                            </div>
                            
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="pt-0 pb-2">
                                        <label>{{form.first_name.label}}:</label>
                                        {{form.first_name}}
                                        {{form.errors.first_name}}
                                        <span class="form-bar"></span>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="pt-0 pb-2">
                                        <label>{{form.last_name.label}}:</label>
                                        {{form.last_name}}
                                        {{form.errors.last_name}}
                                        <span class="form-bar"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="pt-0 pb-2">
                                        <label>{{form.password1.label}}:</label>
                                        {{form.password1}}
                                        {{form.errors.password1}}
                                        <span class="form-bar"></span>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="pt-0 pb-2">
                                        <label>{{form.password2.label}}:</label>
                                        {{form.password2}}
                                        {{form.errors.password2}}
                                        <span class="form-bar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="pt-0 pb-2">
                                        <label>{{form.national_id.label}}:</label>
                                        {{form.national_id}}
                                        {{form.errors.national_id}}
                                        <span class="form-bar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="pt-0 pb-2">
                                        <label>{{form.mobile_tel.label}}:</label>
                                        {{form.mobile_tel}}
                                        {{form.errors.mobile_tel}}
                                        <span class="form-bar"></span>
                                    </div>
                                </div>
                                <div class="col-sm-6">

                                    <div class="pt-0 pb-2">
                                        <label>{{form.organization.label}}:</label>
                                        {{form.organization}}
                                        {{form.errors.organization}}
                                        <span class="form-bar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="pt-0 pb-2">
                                        <label>{{form.sub_organization.label}}:</label>
                                        {{form.sub_organization}}
                                        {{form.errors.sub_organization}}
                                        <span class="form-bar"></span>
                                    </div>
                                </div>
                                <div class="col-sm-6">

                                    <div class="pt-0 pb-2">
                                        <label>{{form.department.label}}:</label>
                                        {{form.department}}
                                        {{form.errors.department}}
                                        <span class="form-bar"></span>
                                    </div>
                                </div>
                            </div>


                            <div class="alert alert-secondary p-0 pl-1" role="alert">
                                User Agreements:
                            </div>
                            <div class="row">
                                <div class="col-12" style="overflow-y: scroll; height: 150px;">
                                    content
                                    <br>.
                                    <br>.
                                    <br>.

                                    <br>
                                    <br>

                                    <div class="alert alert-info p-1" role="alert">
                                        <div class="form-check">
                                            <input type="checkbox" class="form-check-input" id="exampleCheck1"
                                                name="user_agree" value="ok" required>
                                            <label class="form-check-label" for="exampleCheck1">I, hereby, read and
                                                accept the agreements of using the system.</label>
                                        </div>
                                    </div>

                                </div>
                            </div>


                            <div class="row mt-2 text-left">
                                <div class="col-12">

                                    <div class="forgot-phone text-right float-right">
                                        <a href="{% url 'MainApp:home' %}" class="text-right f-w-600">Login</a>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-md-12">
                                    <button class="btn btn-primary btn-md btn-block waves-effect text-center m-b-20"
                                        name="registerbtn" type="submit">{% trans "Sign Up" %} </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock document_container %}